MD002: false # First heading should be a top level heading
MD013: false # Line length
MD024: { siblings_only: true } # Multiple headings with the same content
MD040: false # Fenced code blocks should have a language specified
MD041: false # First line in file should be a top level heading