# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
title: NESNILNEHC's Personal Website
# email: your-email@example.com
email: nesnilnehc@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  NESNILNEHC的个人网站 - 分享技术博客、学习心得和个人见解。这里记录着我在软件开发、
  技术创新和个人成长方面的所思所想。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nesnilnehc.github.io" # the base hostname & protocol for your site
twitter_username: nesnilnehc
github_username:  nesnilnehc

# Post settings
show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Include pages directory
include:
  - _pages

# Header pages (specify the exact order you want)
header_pages:
  - _pages/news.md
  - index.md
  - _pages/tech.md
  - _pages/tutorials.md
  - _pages/about.markdown

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Category settings
category_archive:
  type: liquid
  path: /categories/

# Feed settings
feed:
  path: feed.xml
  posts_limit: 20

# SEO settings
twitter:
  username: nesnilnehc
  card: summary

social:
  name: NESNILNEHC
  links:
    - https://twitter.com/nesnilnehc
    - https://github.com/nesnilnehc

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

# Minima theme settings
minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: nesnilnehc
    github: nesnilnehc

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
